#### Nombre y Apellido: Gabriel Nahuel Lobo, Marcela Varela, Vanina Gigena Canestraro

In [ ]:
# 1er Ejercicio: Obtener los datos completos de los empleados
# Colocar Password (en bloque python) correspondiente antes de ejecutar

#MySQL
SELECT * FROM employees;

#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            # En este caso no necesitamos limpiar ningún dato
            # Para probar, agregar al final de la sentencia SQL, por ejemplo, LIMIT 100
            cursor.execute("SELECT * FROM employees;")
 
            # Con fetchall traemos todas las filas
            employees = cursor.fetchall()
 
            # Recorrer e imprimir
            for emp in employees:
                print(emp)
    finally:
        # cierra la conexión
        conexion.close()
    
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [ ]:
# 2do Ejercicio: Obtener los datos completos de los departamentos.
# Colocar Password (en bloque python) correspondiente antes de ejecutar

#MySQL
SELECT *
FROM departments

#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            # En este caso no necesitamos limpiar ningún dato
            cursor.execute("SELECT * FROM departments;")
 
            # Con fetchall traemos todas las filas
            employees = cursor.fetchall()
 
            # Recorrer e imprimir
            for emp in employees:
                print(emp)
    finally:
        conexion.close()
    
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [ ]:
# 3er Ejercicio: Obtener la cantidad de empleados de sexo femenino.
# Colocar Password (en bloque python) correspondiente antes de ejecutar

#MySQL
SELECT emp_no, last_name FROM employees WHERE gender ='F'


#Desde Python
# Obtenemos los masculinos
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            # Como ya se hizo la consulta para femenino en la práctica, aquí traemos gender ='M'
            consulta = "SELECT emp_no, last_name FROM employees WHERE gender ='M';"
            cursor.execute(consulta)
 
            # Con fetchall traemos todas las filas
            employees = cursor.fetchall()
 
            # Recorrer e imprimir
            for emp in employees:
                print(emp)
    finally:
        conexion.close()
    
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [ ]:
# 4to Ejercicio: Obtener los empleados que son o han sido "staff". Recordar que es una consulta multi tablas.
# Colocar Password (en bloque python) correspondiente antes de ejecutar

#MySQL
SELECT emp.*
FROM employees emp
INNER JOIN titles tit
ON emp.emp_no = tit.emp_no
WHERE title= "Staff"


#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            consulta = "SELECT emp.* FROM employees emp INNER JOIN titles tit ON emp.emp_no = tit.emp_no WHERE title= 'Staff';"
            cursor.execute(consulta)
 
            # Con fetchall traemos todas las filas
            employees = cursor.fetchall()
 
            # Recorrer e imprimir
            for emp in employees:
                print(emp)
    finally:
        conexion.close()
    
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [4]:
# 5to Ejercicio: Agregar el departamento Cienca de Datos.
# Colocar Password (en bloque python) correspondiente antes de ejecutar


#MySQL
INSERT INTO departments (dept_no, dept_name) VALUES ('d010', 'Data Science')

#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='*********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            # Para saber qué Id de dept_no insertar, busco el máximo dept_no que existe:
            # SELECT max(dept_no) FROM departments e inserto el siguiente
            consulta = "INSERT INTO departments (dept_no, dept_name) VALUES (%s, %s);"
            cursor.execute(consulta, ('d010', 'Data Science'))
           
        conexion.commit()
    finally:
        conexion.close()
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [5]:
# 6to Ejercicio: # Agregar el empleado "Pepito" y hacerlo jefe ("manager") del departamento Cienca de Datos.

#MySQL
INSERT INTO employees(emp_no, birth_date, first_name, last_name, gender, hire_date) VALUES ('500001', '1985-02-28','Pepito', 'Perez','M','2010-01-01');
# se agrega en tabla dept_manager para asociar el puesto
INSERT INTO dept_manager(emp_no, dept_no, from_date, to_date) VALUES ('500001', 'd010','2010-01-01','9999-01-01');

#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='*********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            #Como el num de empleado ya existe, busco el maximo emp_no con la siguiente query
            # SELECT max(emp_no) FROM employees e inserto el siguiente
            consulta = "INSERT INTO employees(emp_no, birth_date, first_name, last_name, gender, hire_date) VALUES (%s, %s, %s, %s, %s, %s);"
            cursor.execute(consulta, ('500001', '1985-02-28','Pepito', 'Perez','M','2010-01-01'))
            consulta1 = "INSERT INTO dept_manager(emp_no, dept_no, from_date, to_date) VALUES (%s, %s, %s, %s);"
            cursor.execute(consulta1, ('500001', 'd010','2010-01-01','9999-01-01'))
           
        conexion.commit()
    finally:
        conexion.close()
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [10]:
# 7er Ejercicio: Borrar el empleado "Pepito".


#MySQL
# MySql no permite eliminar registro si en el WHERE no colocamos la Primary Key
DELETE FROM employees
WHERE emp_no= 500001;
# También se elimina de la tabla de puestos
DELETE FROM dept_manager
WHERE emp_no = 500001;


#Desde Python
import pymysql
try:
    conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='*********',
                             db='employees')
    try:
        with conexion.cursor() as cursor:
            consulta = "DELETE FROM employees WHERE emp_no = 500001;"
            cursor.execute(consulta)
            consulta1 = "DELETE FROM  dept_manager WHERE emp_no = 500001;"
            cursor.execute(consulta1)
           
        conexion.commit()
    finally:
        conexion.close()
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
    print("Ocurrió un error al conectar: ", e)

In [ ]:
# 8vo Ejercicio: Obtener el promedio de salarios por departamento.

#MySql
# Se joinea con LEFT con la tabla salarios y departamentos para  traer siempre la info que coincide en dept_emp
SELECT dee.dept_no AS Departamento, dep.dept_name AS Nombre_Departamento, ROUND(AVG(sal.salary),2) AS Promedio_salarios
FROM dept_emp dee
LEFT JOIN salaries sal
ON sal.emp_no = dee.emp_no
LEFT JOIN departments dep
ON dep.dept_no=dee.dept_no
GROUP BY dep.dept_name